SidokApp/Controllers/DokterController.cs
using MessagePack;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Identity.Web;
using SidokApp.Models.Dto;
using SidokApp.Services.Interfaces;
using System.Collections.Generic;

namespace SidokApp.Controllers
{
    public class DokterController : Controller
    {
        private readonly IDokterService _dokterService;
        private readonly ISpesialisasiService _spesialisasiService;
        private readonly ISpesialisasiDokterService _spesialisasiDokterService;
        private readonly IJadwalJagaService _jadwalJagaService;

        public DokterController(IDokterService dokterService, ISpesialisasiService spesialisasiService, 
            ISpesialisasiDokterService spesialisasiDokterService, IJadwalJagaService jadwalJagaService)
        {
            _dokterService = dokterService;
            _spesialisasiService = spesialisasiService;
            _spesialisasiDokterService = spesialisasiDokterService;
            _jadwalJagaService = jadwalJagaService;
        }

        // GET: Dokter
        public async Task<IActionResult> Index()
        {
            var model = await _dokterService.SelectAll();
            return View(model);
        }

        // GET: Dokter/Details/5
        public async Task<IActionResult> Details(string Nik)
        {
            var dokterDto = await _dokterService.SelectByNik(Nik);
            if (Nik == null || dokterDto == null)
            {
                return NotFound();
            }
            ViewData["JadwalJaga"] = await _jadwalJagaService.SelectByDokter(dokterDto.Id);
            return View(dokterDto);
        }

        // GET: Dokter/Create
        public async Task<IActionResult> Create()
        {
            var spesialisasi = await _spesialisasiService.SelectAll();
            ViewData["Spesialisasi"] = spesialisasi.Select(x => new SelectListItem { Text=x.Nama, Value=Convert.ToString(x.Id) }).ToList();
            return View();
        }

        // POST: Dokter/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nama,Nip,Nik,TanggalLahir,TempatLahir,JenisKelamin,IdSpesialisasi")] DokterDto dokterDto)
        {
            if (ModelState.IsValid)
            {
                await _dokterService.Insert(dokterDto);
                return RedirectToAction(nameof(Index));
            }
            return View(dokterDto);
        }

        // GET: Dokter/Edit/5
        public async Task<IActionResult> Edit(string nik)
        {
            var dokterDto = await _dokterService.SelectByNik(nik);
            if (nik == null || dokterDto == null)
            {
                return NotFound();
            }

            var spesialisasi = await _spesialisasiService.SelectAll();
            List<SelectListItem> spesialisasiList = spesialisasi.Select(x => new SelectListItem { Text = x.Nama, Value = Convert.ToString(x.Id) }).ToList();
            var selected = spesialisasiList.Find(x => x.Value == dokterDto.IdSpesialisasi.ToString());
            selected.Selected = true;
            ViewData["Spesialisasi"] = spesialisasiList;
            return View(dokterDto);
        }

        // POST: Dokter/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string nik, [Bind("Nama,Nip,Nik,TanggalLahir,TempatLahir,JenisKelamin,IdSpesialisasi")] DokterDto dokterDto)
        {
            if (nik != dokterDto.Nik)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _dokterService.Update(dokterDto);
               
                return RedirectToAction(nameof(Index));
            }
            return View(dokterDto);
        }

        // GET: Dokter/Delete/5
        public async Task<IActionResult> Delete(string nik)
        {
            var dokterDto = await _dokterService.SelectByNik(nik);
            if (dokterDto == null)
            {
                return NotFound();
            }

            return View(dokterDto);
        }

        // POST: Dokter/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string nik)
        {
            await _dokterService.Delete(nik);
            return RedirectToAction(nameof(Index));
        }
    }
}

SidokApp/Controllers/JadwalController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SidokApp.Models.Dto;
using SidokApp.Repository.Interfaces;
using SidokApp.Services.Interfaces;

namespace SidokApp.Controllers
{
    public class JadwalController : Controller
    {
        private readonly IPoliService _poliService;
        private readonly IDokterService _dokterService;
        private readonly IJadwalJagaService _jadwalJagaService;
        public JadwalController(IPoliService poliService, IDokterService dokterService, IJadwalJagaService jadwalJagaService) 
        {
            _poliService = poliService;
            _dokterService = dokterService;
            _jadwalJagaService = jadwalJagaService;
        }
        // GET: JadwalJagaController/Create
        public async Task<IActionResult> Create(string nik)
        {
            var poli = await _poliService.SelectAll();
            var dokter =await  _dokterService.SelectByNik(nik);
            JadwalJagaDto jadwalDto = new JadwalJagaDto
            {
                IdDokter = dokter.Id,
                NamaDokter = dokter.Nama
            };
            ViewData["poli"] = poli.Select(x => new SelectListItem { Text = x.Nama, Value = Convert.ToString(x.Id) }).ToList();
            return View(jadwalDto);
        }

        // POST: JadwalJagaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Hari, IdDokter, IdPoli")] JadwalJagaDto jadwalDokter)
        {
            try
            {
                await _jadwalJagaService.Insert(jadwalDokter);
                return RedirectToAction("Index", "Dokter");
            }
            catch
            {
                return View(jadwalDokter);
            }
        }
    }
}

SidokApp/Views/Dokter/Create.cshtml
@model SidokApp.Models.Dto.DokterDto

@{
    ViewData["Title"] = "Create";
    var spesialisasi = (IEnumerable<SelectListItem>)ViewData["Spesialisasi"];
}

<h1>Tambah Dokter</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Nip" value="-" />
            <div class="form-group">
                <label asp-for="Nama" class="control-label"></label>
                <input asp-for="Nama" class="form-control" />
                <span asp-validation-for="Nama" class="text-danger"></span>
           </div>

            @*<div class="form-group">
                <label class="control-label">NIP</label>
                <input asp-for="Nip" class="form-control" />
                <span asp-validation-for="Nip" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label class="control-label">NIK</label>
                <input asp-for="Nik" class="form-control" />
                <span asp-validation-for="Nik" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Tanggal lahir</label>
                <input asp-for="TanggalLahir" class="form-control" />
                <span asp-validation-for="TanggalLahir" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Tempat Lahir</label>
                <input asp-for="TempatLahir" class="form-control" />
                <span asp-validation-for="TempatLahir" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Jenis Kelamin</label>
                <select class="form-control" asp-for="JenisKelamin">
                    <option>--Pilih Jenis Kelamin--</option>
                    <option value="1">Laki-Laki</option>
                    <option value="2">Perempuan</option>
                </select>
                <span asp-validation-for="JenisKelamin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Spesialisasi</label>
                <select class ="form-control" asp-for="IdSpesialisasi" asp-items="spesialisasi">
                    <option>--Pilih Spesialisasi--</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Simpan" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Kembali ke Beranda</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SidokApp/Views/Dokter/Delete.cshtml
@model SidokApp.Models.Dto.DokterDto

@{
    ViewData["Title"] = "Delete";
}

<h1>Hapus Dokter</h1>

<h3>Apakah anda yaking ingin menghapus data ini?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
          Nama
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nama)
        </dd>
        <dt class = "col-sm-2">
           NIP
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nip)
        </dd>
        <dt class = "col-sm-2">
            NIK
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nik)
        </dd>
        <dt class = "col-sm-2">
            Tanggal Lahir
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TanggalLahir)
        </dd>
        <dt class = "col-sm-2">
            Tempat Lahir
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TempatLahir)
        </dd>
        <dt class = "col-sm-2">
            Jenis Kelamin
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JenisKelaminString)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Spesialisasi)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Spesialisasi)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Nik" />
        <input type="submit" value="Hapus" class="btn btn-danger" /> |
        <a asp-action="Index">Kembali ke Beranda</a>
    </form>
</div>

SidokApp/Views/Dokter/Details.cshtml
@using SidokApp.Models.Dto;
@model SidokApp.Models.Dto.DokterDto

@{
    ViewData["Title"] = "Details";
    var jadwalJaga = (IEnumerable <JadwalJagaDto>)ViewData["JadwalJaga"];
}

<h1>Detail Dokter</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nama)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nama)
        </dd>
        <dt class = "col-sm-2">
            NIP
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nip)
        </dd>
        <dt class = "col-sm-2">
           NIK
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nik)
        </dd>
        <dt class = "col-sm-2">
            Tanggal Lahir
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TanggalLahir)
        </dd>
        <dt class = "col-sm-2">
            Tempat Lahir
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TempatLahir)
        </dd>
        <dt class = "col-sm-2">
            Jenis Kelamin
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JenisKelaminString)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Spesialisasi)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Spesialisasi)
        </dd>
    </dl>
</div>

<table class="table">
    <thead>
        <tr>

            <th>
                Nama Poli
            </th>
            <th>
                Lokasi
            <th>
                Jadwal
            </th>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in jadwalJaga)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.NamaPoli)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Lokasi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Jadwal)
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    <a asp-action="Edit" asp-route-nik="@Model?.Nik">Ubah</a> |
    <a asp-action="Index">Kembali ke Beranda</a>
</div>

SidokApp/Views/Dokter/Edit.cshtml
@model SidokApp.Models.Dto.DokterDto

@{
    ViewData["Title"] = "Edit";
    var spesialisasi = (IEnumerable<SelectListItem>)ViewData["Spesialisasi"];
}

<h1>Ubah Dokter</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Nip" />
            <input type="hidden" asp-for="Nik" />
            <div class="form-group">
                <label asp-for="Nama" class="control-label"></label>
                <input asp-for="Nama" class="form-control" />
                <span asp-validation-for="Nama" class="text-danger"></span>
            </div>
           @* <div class="form-group">
                <label asp-for="Nip" class="control-label"></label>
                <input asp-for="Nip" class="form-control" />
                <span asp-validation-for="Nip" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Nik" class="control-label"></label>
                <input asp-for="Nik" class="form-control" disabled />
                <span asp-validation-for="Nik" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TanggalLahir" class="control-label"></label>
                <input asp-for="TanggalLahir" class="form-control" />
                <span asp-validation-for="TanggalLahir" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TempatLahir" class="control-label"></label>
                <input asp-for="TempatLahir" class="form-control" />
                <span asp-validation-for="TempatLahir" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Jenis Kelamin</label>
                <select class="form-control" asp-for="JenisKelamin">
                    <option>--Pilih Jenis Kelamin--</option>
                    <option value="1">Laki-Laki</option>
                    <option value="2">Perempuan</option>
                </select>
            </div>
            <div class="form-group">
                <label class="control-label">Spesialisasi</label>
                <select class="form-control" asp-for="IdSpesialisasi" asp-items="spesialisasi">
                    <option>--Pilih Spesialisasi--</option>
                </select>
            </div>
         
            <div class="form-group">
                <input type="submit" value="Simpan" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Kembali ke Beranda</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SidokApp/Views/Dokter/Index.cshtml
@model IEnumerable<SidokApp.Models.Dto.DokterDto>

@{
    ViewData["Title"] = "Index";
}

<h1>Sistem Informasi Dokter</h1>

<p>
    <a asp-action="Create">Tambah Dokter</a>
</p>
<table class="table">
    <thead>
        <tr>
           
            <th>
               Nama Dokter
            </th>
            <th>
                NIP
            </th>
            <th>
              NIK
            </th>
            <th>
                Jenis Kelamin
            </th>
            <th>
               Spesialisasi
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
           
            <td>
                <a asp-action="Details" asp-route-nik="@item.Nik">@Html.DisplayFor(modelItem => item.Nama)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nip)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nik)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JenisKelaminString)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Spesialisasi)
                </td>
            <td>
                <a asp-controller="Jadwal" asp-action="Create" asp-route-nik="@item.Nik">Tambah Jadwal</a> |
                <a asp-action="Edit" asp-route-nik="@item.Nik">Ubah</a> |
                <a asp-action="Delete" asp-route-nik="@item.Nik">Hapus</a>
            </td>
        </tr>
}
    </tbody>
</table>